version: '3'

services:
  postgresdb:
    container_name: postgresql
    image: postgres
    restart: always
    ports:
      - ${EXTERNAL}:${INTERNAL}
    volumes:
      - ${CURR}/${DATA_DIR}:/var/lib/postgresql/data
      - ${CURR}/${DB_CONFIG_DIR}/${DB_CONFIG}:/etc/postgresql/postgres.conf
      # - ${CURR}/${DB_CONFIG_DIR}/${DB_CONFIG}:/var/lib/postgresql/data/postgres.conf
    environment:
      POSTGRES_USER: ${ADMIN_USER}
      POSTGRES_PASSWORD: ${ADMIN_PASS}
      POSTGRES_DB: ${ADMIN_DB}
      # command: postgres -c config_file=/etc/postgresql/postgres.conf
      
  pgadminpage:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - ${PGA_EXTERNAL}:${PGA_INTERNAL}
    environment:
     - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_USER}
     - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASS}

networks:
  default:
    external: true
    name: postgres-network
