version: '3'

services:
  db:
    container_name: postgresql
    image: postgres
    restart: always
    ports:
      - ${EXTERNAL}:${INTERNAL}
    volumes:
      - ${CURR}/${DATA_DIR}:/var/lib/postgresql/data
      - ${CURR}/${DB_CONFIG_DIR}/${DB_CONFIG}:/etc/postgresql/postgres.conf
    environment:
      POSTGRES_USER: ${ADMIN_USER}
      POSTGRES_PASSWORD: ${ADMIN_PASS}

      
