version: "3"
services:
  mariadb:
    container_name: maria
    # if use registry server: 0.0.0.0:443/mariadb
    image: mariadb:latest
    restart: always
    ports: 
      - ${EXTERNAL}:${INTERNAL}
    volumes:
      - ${CURR}/${DATA_DIR}:/var/lib/mysql
      - ${CURR}/${DB_CONFIG_DIR}/${DB_CONFIG}:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS} # Must be changed
      MYSQL_USER: ${ADMIN_USER}
      MYSQL_PASSWORD: ${ADMIN_PASS}
      MYSQL_DATABASE: ${ADMIN_DB}
      TZ: Asia/Seoul

# networks:
#   default:
#     name: maria-network
