# Use root/example as user/password credentials
version: '3.1'

services:
  mongodb: 
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /Users/1eedaegon/workspace/coding_practice/storage/storage-container-practice/mongodb/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    # command: 
     # - mongo admin --host localhost:27017 -u root -p root --eval "db.createUser({user:'app',pwd:'app',roles:[{role:'userAdminAnyDatabase',db:'v-tube'}]});"
     #
# if use docker network
networks:
  default:
    external: true
    name: mongo-network
